import { StyleSheet, TextStyle } from 'react-native';
import colors from '../../../styles/colors';
import typography from '../../../styles/typography';
import spacing from '../../../styles/spacing';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transitionContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 20,
  },
  background: {
    flex: 1,
    width: '100%',
    resizeMode: 'cover',
    justifyContent: 'center',
    paddingVertical: spacing.medium,
  },
  title: {
    fontFamily: 'Merriweather-Bold',
    textShadowRadius: 10,
    textShadowColor: colors.text,
    fontSize: typography.fontSizeLarge * 1.05,
    padding: spacing.large,
    paddingBottom: spacing.small,
    color: colors.whiteText,
    borderRadius: 5,
    marginTop: spacing.large,
    textAlign: 'center',
  },
  titleModal: {
    fontFamily: 'Merriweather-Bold',
    textShadowRadius: 10,
    textShadowColor: colors.text,
    fontSize: typography.fontSizeLarge * 1.05,
    padding: spacing.large,
    paddingBottom: spacing.small,
    color: colors.whiteText,
    borderRadius: 5,
    marginVertical: spacing.medium,
    textAlign: 'center',
  },
  title2: {
    width: '100%',
    fontFamily: 'LOKICOLA',
    textShadowRadius: 10,
    textShadowColor: 'rgba(7, 174, 252, 0.8)',
    fontSize: 70,
    color: colors.whiteText,
    borderRadius: 5,
    textAlign: 'center',
    marginBottom: spacing.large,
  },
  subtitle: {
    fontFamily: 'Merriweather-BoldItalic',
    fontSize: typography.fontSizeMedium,
    textShadowRadius: 10,
    textShadowColor: colors.text,
    color: colors.whiteText,
    padding: spacing.small,
    marginBottom: 10,
    textAlign: 'center',
    borderRadius: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    boxShadow: '0 0 10px 0.5px rgba(0, 0, 0, 0.5)',
  },
  skillsContainer: {
    marginTop: 10,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  skillText: {
    fontWeight: typography.fontWeightBold,
    fontSize: 15,
    textShadowRadius: 3,
    textShadowColor: colors.text,
    color: colors.whiteText,
    textAlign: 'center',
    padding: 10,
    margin: spacing.small,
    borderRadius: 5,
    borderTopWidth: 1,
    borderBottomWidth: 2,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomColor: colors.text,
    backgroundColor:'rgba(219, 180, 6, 0.67)',
  },
  unlockedMessage: {
    fontWeight: typography.fontWeightBold,
    fontSize: typography.fontSizeMedium,
    textShadowRadius: 10,
    textShadowColor: colors.text,
    backgroundColor: 'rgba(19, 211, 83, 0.25)',
    boxShadow: '0 0 10px 0.25px rgba(255, 255, 255, 0.84)',
    borderRadius: 5,
    padding: 10,
    color: colors.white,
    margin: spacing.large,
    textAlign: 'center',
  },
  separatorText: {
    fontFamily: 'Merriweather-BoldItalic',
    fontSize: typography.fontSizeSmall,
    paddingVertical: 10,
    textShadowRadius: 10,
    textShadowColor: colors.text,
    color: colors.buttonText,
  },
  continueButton: {
    textShadowRadius: 10,
    textShadowColor: colors.text,
    boxShadow: '0 0 10px 0.25px rgba(255, 255, 255, 0.64)',
    borderRadius: 10,
    marginBottom: 0,
    alignItems: 'center',
  },
  continueStoryButton: {
    borderRadius: 10,
    marginBottom: 0,
    backgroundColor: 'rgba(219, 180, 6, 0.67)',
    borderWidth: 0.7,
    alignItems: 'center',
  },
  continueButtonText: {
    fontFamily: 'Merriweather-Bold',
    fontSize: typography.fontSizeSuperMedium,
    textShadowRadius: 10,
    textShadowColor: colors.text,
    color: colors.buttonText,
    textAlign: 'center',
  },
  careerButton: {
    borderRadius: 8,
},
  selectedCareerButton: {
    backgroundColor: "rgba(245, 136, 12, 0.64)",
    borderColor: "rgba(245, 136, 12, 0.34)",
    borderStyle: "dashed",
    borderWidth: 2,
  },
  careerText: {
    fontFamily: 'Merriweather-BoldItalic',
    textShadowRadius: 10,
    textShadowColor: colors.text,
    color: colors.whiteText,
    backgroundColor: 'rgba(19, 211, 83, 0.25)',
    boxShadow: '0 0 10px 0.25px rgba(7, 7, 7, 0.6)',
    borderRadius: 8,
    padding: spacing.medium - 5,
    marginBottom: spacing.medium,
    alignItems: 'center',
    borderColor: "#0056b3",
    fontSize: 18,
    textAlign: "center",
    marginVertical: spacing.small + 2,
},
  confirmButton: {
    backgroundColor: 'rgba(19, 150, 211, 1)',
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginTop: 20,
},
disabledButton: {
  borderRadius: 10,
  marginBottom: 0,
  backgroundColor: 'rgba(255, 255, 255, 0.35)',
},
confirmButtonText: {
  fontFamily: 'Merriweather-BoldItalic',
  textShadowRadius: 10,
  textShadowColor: colors.text,
  color: colors.whiteText,
  borderRadius: 8,
  alignItems: 'center',
  borderColor: "#0056b3",
  fontSize: 18,
  textAlign: "center",
},
cancelButton: {
  marginTop: spacing.large + 5,
  padding: 10,
  alignItems: "center",
  backgroundColor: 'rgba(255, 255, 255, 0.35)',
  borderRadius: 8,
},
cancelButtonText: {
  fontFamily: 'Merriweather-Bold',
  textShadowRadius: 10,
  textShadowColor: colors.text,
  color: colors.whiteText,
  fontSize: 18,
},
});

export default styles;
