import { StyleSheet, ScrollView } from 'react-native';
import colors from '../../../styles/colors';
import spacing from '../../../styles/spacing';
import typography from '../../../styles/typography';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  scrollContainer: {
    alignItems: 'center',
    paddingBottom: spacing.large,
  },
  hud: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: spacing.large,
    marginBottom: spacing.medium,
  },
  hudText: {
    fontFamily: 'Merriweather-BoldItalic',
    marginTop: spacing.extraLarge,
    paddingVertical: spacing.medium,
    fontSize: typography.fontSizeMedium,
    color: colors.whiteText,
  },
  hudTitle: {
    fontFamily: 'Merriweather-BoldItalic',
    marginBottom: spacing.large,
    paddingHorizontal: spacing.medium,
    paddingVertical: spacing.small,
    fontSize: typography.fontSizeLarge,
    color: colors.whiteText,
    backgroundColor: colors.secondary,
    borderRadius: spacing.large,
    textShadowRadius: 10,
    textShadowColor: colors.whiteText,
    boxShadow: '0 0 10px 0.25px rgba(255, 255, 255, 0.25)',
  },
  adventureImage: {
    width: '96%',
    height: 300,
    borderRadius: 10,
    marginBottom: spacing.large,
    boxShadow: '0 0 10px 0.25px rgba(255, 255, 255, 0.39)',
  },
  adventureText: {
    width: '100%',
    overflow: 'scroll',
    fontFamily: 'Merriweather-BoldItalic',
    fontSize: typography.fontSizeSuperMedium,
    textShadowRadius: 5,
    textShadowColor: colors.text,
    color: colors.whiteText,
    textAlign: 'center',
    marginVertical: spacing.small,
    paddingHorizontal: spacing.medium,
  },
  choicesContainer: {
    width: '100%',
    marginTop: spacing.extraLarge,
    paddingHorizontal: spacing.medium
  },
  choiceButton: {
    backgroundColor: colors.secondary,
    borderRadius: 8,
    padding: spacing.medium,
    marginBottom: spacing.large,
    alignItems: 'center',
  },
  choiceButtonText: {
    fontFamily: 'Merriweather-Bold',
    fontSize: typography.fontSizeSuperMedium,
    textShadowRadius: 10,
    textShadowColor: colors.text,
    color: colors.buttonText,
    textAlign: 'center',
  },
  consequenceTitle: {
    width: '100%',
    fontSize: typography.fontSizeLarge,
    fontFamily: 'Merriweather-Bold',
    textShadowRadius: 5,
    textShadowColor: colors.text,
    color: colors.whiteText,
    padding: spacing.medium,
    textAlign: 'center',
},
consequenceText: {
    width: '100%',
    fontSize: typography.fontSizeSuperMedium,
    fontFamily: 'Merriweather-BoldItalic',
    textShadowRadius: 15,
    textShadowColor: colors.text,
    color: colors.whiteText,
    marginBottom: spacing.large,
    padding: spacing.medium,
    textAlign: 'center',
},
skillTitle: {
  width: '94%',
  fontSize: typography.fontSizeLarge,
  fontFamily: 'Merriweather-BoldItalic',
  color: colors.whiteText,
  textAlign: 'center',
  textShadowRadius: 5,
  textShadowColor: colors.text,
  marginVertical: spacing.extraLarge,
  backgroundColor: colors.secondary,
  borderRadius: spacing.small,
  boxShadow: '0 0 10px 0.25px rgb(9, 255, 0)',
  padding: spacing.small,
  transform: 'rotate',
},
nextButton: {
  backgroundColor: colors.primary,
    paddingVertical: spacing.medium,
    paddingHorizontal: spacing.extraLarge,
    borderRadius: spacing.small,
    boxShadow: '0 0 10px 0.25px rgba(255, 255, 255, 0.5)',
  },
  nextButtonText: {
    fontFamily: 'Merriweather-Bold',
    fontSize: typography.fontSizeMedium,
    textShadowRadius: 5,
    textShadowColor: colors.text,
    color: colors.white,
    textAlign: 'center',
},
  errorText: {
    fontSize: typography.fontSizeSmall,
    color: colors.error,
    textAlign: 'center',
    marginTop: spacing.medium,
  },
  transitionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
},
transitionText: {
    fontSize: 100,
    fontFamily: 'Merriweather-Bold',
    color: '#fff',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
},
transitionButton: {
    marginTop: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    padding: 12,
    borderRadius: 8,
    boxShadow: '0 0 10px 0.25px white',
},
transitionButtonText: {
  fontFamily: 'Merriweather-Bold',
  fontSize: typography.fontSizeMedium,
  textShadowRadius: 5,
  textShadowColor: colors.text,
  color: colors.white,
  textAlign: 'center',
},
});

export default styles;
